# Generated by Django 6.0.1 on 2026-02-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='semester',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='year_level',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name='prospectusentry',
            index=models.Index(fields=['year_level', 'semester'], name='registrar_p_year_le_9959be_idx'),
        ),
        migrations.AddIndex(
            model_name='prospectusentry',
            index=models.Index(fields=['program', 'year_level', 'semester'], name='registrar_p_program_d238e5_idx'),
        ),
    ]
