# Generated by Django 6.0.1 on 2026-02-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_alter_academicterm_semester_alter_section_year_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='adviser_approval_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='adviser_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='civil_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dean_approval_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='dean_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='elementary_school',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='student',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='extension_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='father_contact_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='junior_high_school',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_contact_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_maiden_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='student',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='senior_high_school',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='student',
            name='senior_high_track_strand',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_load_schedule',
            field=models.TextField(blank=True),
        ),
    ]
