# Generated by Django 6.0.1 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_student_academic_year_student_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
    ]
