# Generated by Django 6.0.1 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0004_allow_duplicate_names_and_section_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_adviser',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='program',
            name='school_dean',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
