# Generated by Django 6.0.1 on 2026-02-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0005_program_adviser_and_dean'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectusentry',
            name='academic_year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='prospectusentry',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectus_entries', to='registrar.section'),
        ),
        migrations.AlterUniqueTogether(
            name='prospectusentry',
            unique_together={('program', 'subject', 'year_level', 'semester', 'academic_year', 'section')},
        ),
        migrations.RemoveIndex(
            model_name='prospectusentry',
            name='registrar_p_program_d238e5_idx',
        ),
        migrations.AddIndex(
            model_name='prospectusentry',
            index=models.Index(fields=['program', 'year_level', 'semester', 'academic_year', 'section'], name='registrar_p_program_6b2b34_idx'),
        ),
    ]
