# Generated by Django 6.0.1 on 2026-02-27 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0006_prospectusentry_academic_year_and_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('year_level', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('status', models.CharField(default='ongoing', max_length=20)),
                ('start_date', models.DateField()),
                ('adviser_name', models.CharField(blank=True, max_length=120)),
                ('adviser_approval_status', models.CharField(default='pending', max_length=20)),
                ('dean_name', models.CharField(blank=True, max_length=120)),
                ('dean_approval_status', models.CharField(default='pending', max_length=20)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrar.program')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrar.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='registrar.student')),
            ],
            options={
                'ordering': ['-academic_year', '-semester'],
                'unique_together': {('student', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='AcademicSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credits', models.DecimalField(decimal_places=1, max_digits=4)),
                ('status', models.CharField(default='enrolled', max_length=20)),
                ('academic_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='registrar.academichistory')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrar.subject')),
            ],
            options={
                'unique_together': {('academic_history', 'subject')},
            },
        ),
    ]
