# Generated by Django 6.0.1 on 2026-02-27 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0007_academichistory_academicsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='academichistory',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='civil_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='course',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='elementary_school',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='extension_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='father_contact_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='father_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='first_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='junior_high_school',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='last_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='middle_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='mother_contact_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='mother_maiden_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='nationality',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='scholarship',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='senior_high_school',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='senior_high_track_strand',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='sex',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='academichistory',
            name='subject_load_schedule',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='academichistory',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='registrar.section'),
        ),
    ]
